apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonial
  namespace: goats
  labels:
    app: bonial-1
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bonial-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bonial-1
    spec:
      containers:
      - name: one-goat
        image: registry.bonial.org/public/demo-kekse-k8s
        ports:
        - containerPort: 8080